# Generated by Django 3.2.4 on 2021-06-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(related_name='product_basket', to='shop.Product'),
        ),
    ]
